### ISSUE TITLE
Compatibility of Canopy2 with 10x Genomics Sequencing Data

### ISSUE THREAD

**Issue by helnSYSUCC** [annweideman/canopy2#1]
I would like to express my gratitude for developing such an amazing and practical tool! It has been incredibly helpful for single-cell data processing.

However, while following the provided preprocessing script, I noticed that the tool does not seem to work as expected with 10X sequencing data. I am wondering if there are specific instructions or adaptations required to make Canopy2 compatible with 10X data?

**Comment by yuchaojiang** [comment]
10X Genomics captures 5' or 3' end of the reads and is not suited to identify SNVs. This is by default developed for full-transcript seq.
